server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

