server:
  port: 8081

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

# Add this to application properties to expose the actuator/info endpoint.
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
