spring:
  application:
    name: websocket-server
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:example@localhost:27017}
      database: ${MONGODB_DATABASE:rt-board}
      auto-index-creation: true

server:
  min-port: 10000
  max-port: 11000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

# The default user='guest' and the password='guest'
broker:
  relay:
    host: ${BROKER_HOST:localhost}

# Add this to application properties to expose the actuator/info endpoint.
management:
  endpoints:
    web:
      exposure:
        include: info

# To see what is going on with MongoDB
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

