version: '3.7'

services:
  rt-eureka:
    restart: unless-stopped
    build:
      context: ./eureka
    volumes:
      - ./config/eureka/application.yml:/app/application.yml:r
    ports:
      - "8761:8761"
    expose:
      - "8761"
 
  rt-gateway:
    restart: unless-stopped
    build:
      context: ./gateway
    environment:
      - EUREKA_URI=http://rt-eureka:8761/eureka
    volumes:
      - ./config/gateway/application.yml:/app/application.yml:r
    ports:
      - "0.0.0.0:9292:8081"
    depends_on:
      - rt-eureka

  rt-websocket-server:
    restart: unless-stopped
    build:
      context: ./websocket-server
    environment:
      - MIN_PORT=10000
      - MAX_PORT=11000
      - EUREKA_URI=http://rt-eureka:8761/eureka
      - BROKER_HOST=playbox
      - MONGODB_URI=mongodb://root:example@playbox:27017/
      - MONGODB_DATABASE=rt-board
    volumes:
      - ./config/websocket-server/application.yml:/app/application.yml:r
      - ./config/websocket-server/app.config.js:/app/public/app.config.js:r
    expose:
      - "10000-11000"
    depends_on:
      - rt-gateway

